stages:  
  - build  
  - deploy  
  - showlog

build:  
  stage: build  
  variables:
    GIT_STRATEGY: clone  # Bước build cần clone code
  script:  
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar  # Lưu JAR để dùng trong deploy
  tags:
    - ubuntu-server

deploy:  
  stage: deploy  
  dependencies: 
    - build  # Chỉ nhận file từ build, không tải lại code từ repo
  script:  
    - ls -l target/  # Kiểm tra file có tồn tại không
    - kill -9 $(ps -ef | grep "shoe-ShoppingCart-0.0.1-SNAPSHOT.jar" | grep -v grep | awk '{print $2}')
    - nohup java -jar target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
  tags:
    - ubuntu-server

showlog:
  stage: showlog
  dependencies: 
    - deploy  # Chỉ nhận file từ build, không tải lại code từ repo
  script:  
    - tail -n 1000 app.log
  tags:
    - ubuntu-server
