stages:  
  - build  
  - deploy  
  - showlog

build:  
  stage: build  
  variables:
    GIT_STRATEGY: clone  # Bước build cần clone code
  script:  
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar  # Lưu JAR để dùng trong deploy
  tags:
    - ubuntu-server

deploy:  
  stage: deploy  
  dependencies: []  # Chỉ nhận file từ build, không tải lại code từ repo
  script:  
    - ls -l target/  # Kiểm tra file có tồn tại không
    - java -jar target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar
  tags:
    - ubuntu-server

