stages:  
  - build  
  - deploy  
  - showlog

build:  
  stage: build  
  variables:
    GIT_STRATERY : clone
  script:  
    - mvn install -DskipTests=True
  tags:
    - ubuntu-server


# deploy:  
#   stage: deploy  
#   variables:
#     GIT_STRATERY : none
#   script:  
#     - sudo cp
#     - mvn install -DskipTests=True
#   tags:
#     - ubuntu-server
    
