stages:  
  - build  
  - deploy  
  - showlog

build:  
  stage: build  
  variables:
    GIT_STRATERY : clone
  script:  
    - mvn install -DskipTests=True
  tags:
    - ubuntu-server

deploy:  
  stage: deploy  
  variables:
    GIT_STRATERY : none
  script:  
    - java -jar target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar
  tags:
    - ubuntu-server
    
